[FEATURE] Add hook dispatcher to review resource owner
xperseguers/t3ext-oidc pull request #77
Opened 2022-01-11 13:00 UTC by buepro

Resolves: #76

2022-07-14 09:00 UTC, xperseguers requested changes

2022-07-14 09:00 UTC, xperseguers commented on Classes/Service/AuthenticationService.php
> +                    trigger_error(
It's not deprecated anymore, you trigger an error and do not call the hook...

2022-07-14 09:00 UTC, xperseguers commented on Classes/Service/AuthenticationService.php
> +        //  Hookfor post-processing the user record
Invalid change of comment

2022-07-14 09:00 UTC, xperseguers commented on Classes/Service/AuthenticationService.php
> +                        'The ResourceOwnerHookInterface is deprecated since 1.1.0 and will be removed in 2.0.0, use the PostProcessResourceOwnerHookInterface instead.',
This will be v1.2.0, not v1.1.0 anymore.

2022-07-19 15:44 UTC, buepro commented on Classes/Service/AuthenticationService.php
> +                    trigger_error(
Actually the hook is called since `ResourceOwnerHookInterface extends PostProcessResourceOwnerHookInterface`.

2023-06-19 11:05 UTC, liayn commented
Newer implementation https://github.com/xperseguers/t3ext-oidc/pull/115

2024-06-22 18:10 UTC, liayn commented
There was no further progress in this PR and the event introduced in #115 should cover this. Closing this therefore.

2024-06-22 18:10 UTC, closed without merging